DATANAME = 'PEMS-BAY'
TIMESTEP_IN = 12
TIMESTEP_OUT = 12 # It can be overrided by param_stgcn3
N_NODE = 325
CHANNEL = 1
BATCHSIZE = 64
LEARN = 0.001
EPOCH = 200
PATIENCE = 10
OPTIMIZER = 'Adam'
# OPTIMIZER = 'RMSprop'
# LOSS = 'MSE'
LOSS = 'MAE'
TRAINRATIO = 0.8 # TRAIN + VAL
TRAINVALSPLIT = 0.125 # val_ratio = 0.8 * 0.125 = 0.1
FLOWPATH = '../PEMSBAY/pems-bay.h5'
ADJPATH = '../PEMSBAY/W_pemsbay.csv'